export const sentences = [
  "The quick brown fox jumps over the lazy dog.",
  "Pack my box with five dozen liquor jugs.",
  "How vexingly quick daft zebras jump.",
  "Sphinx of black quartz, judge my vow.",
  "Two driven jocks help fax my big quiz.",
  "The five boxing wizards jump quickly.",
  "Jackdaws love my big sphinx of quartz.",
  "Crazy Frederick bought many very exquisite opal jewels.",
  "We promptly judged antique ivory buckles for the next prize competition.",
  "A mad boxer shot a quick, gloved jab to the jaw of his opponent.",
  "The jay, pig, fox, zebra and my wolves quack!",
  "Sympathizing would fix Quaker objectives.",
  "Many-wived Jack laughs at probes of sex quiz.",
  "Turgid saxophones blew over Mick's jazzy quiff.",
  "Playing jazz vibe chords quickly excites my wife.",
  "Big July earthquakes confound zany SQL vow.",
  "Foxy diva solutions? Not so, Billy: Far eratic urgent queriesnfidently.",
  "A quick movement of the enemy will jeopardize six gunboats.",
  "A wizard's job is to vex chumps quickly in fog.",
  "Watch Jeopardy, Alex Trebek's fun TV quiz game.",
  "Crazy Frederick bought many very exquisite opal jewels.",
  "We promptly judged antique ivory buckles for the next prize competition.",
  "A mad boxer shot a quick, gloved jab to the jaw of his opponent.",
  "All your base are belong to us.",
  "There is no spoon.",
  "May the Force be with you.",
  "Life finds a way.",
  "Houston, we have a problem.",
  "I'll be back.",
  "Say hello to my little friend.",
  "You talking to me?",
  "Elementary, my dear Watson.",
  "To be or not to be, that is the question.",
  "The only thing we have to fear is fear itself.",
  "I think, therefore I am.",
  "That is the question.",
  "Let them eat cake.",
  "I have a dream.",
  "Yes, we can.",
  "Make it so.",
  "Engage.",
  "Live long and prosper.",
  "The cake is a lie.",
  "It does not compute.",
  "Does not compute.",
  "I am error.",
  "Game over, man. Game over.",
  "Finish him.",
  "Get over here.",
  "Yippee ki-yay.",
  "Bond. James Bond.",
];
